repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.0.1
      hooks:
          - id: check-merge-conflict
          - id: end-of-file-fixer
          - id: mixed-line-ending
            args: [--fix=no]
          - id: trailing-whitespace
    - repo: local
      hooks:
          - id: swiftformat
            name: SwiftFormat
            description: Check swift files for formating issues with SwiftFormat.
            entry: swiftformat
            language: system
            types: [swift]
